acin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('acinsite.urls')),
    path('document/', include('document.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acinsite/urls.py
from django.urls import path
from acinsite import views
app_name='Main'

urlpatterns=[
    path('',views.main, name="main"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    path('intro/',views.intro,name="intro"),
    path('professor/',views.professor,name="professor"),
    path('member/',views.member,name="member"),
    path('project/create/',views.create_project,name="create-project"),
    path('project/delete/<pk>/',views.delete_project,name="delete-project"),
    path('project/modify/list/',views.modify_list,name="modify-list"),
    path('project/ajax/',views.get_ajax_project,name="ajax-project"),
    path('project/',views.project,name="project"),
    path('project/<keyword>/',views.project,name="project"),
    path('gallery/write/',views.write_gallery,name="write-gallery"),
    path('gallery/',views.gallery,name="gallery"),
    path('gallery/detail/<int:pk>/',views.detail_gallery,name="detail-gallery"),
    path('gallery/delete/<int:pk>/',views.delete_gallery,name="delete-gallery"),
    #MYPAGE
    path('mypage/',views.mypage,name="mypage"),
    
    #게시판
    path('board/Viewboard/',views.Viewboard,name="Viewboard"),
    path('board/Writeboard/',views.Writeboard,name="Writeboard"),
    path('board/Viewboard/Boarddetail/<int:pk>',views.Boarddetail,name="Boarddetail"),
    path('board/Viewboard/Boarddetail/Deleteboard/<int:pk>',views.Deleteboard, name="Deleteboard"),
    path('board/Viewboard/Boarddetail/Editboard/<int:pk>',views.Editboard, name="Editboard"),

    #일일보고
    path('Today_Report_Today_Report_Board',views.Today_Report_Board, name="Today_Report_Board"),
    path('Write_Today_Report', views.Write_Today_Report,name="Write_Today_Report"),
    path('Today_Report_detail/<int:pk>/',views.Today_Report_detail,name="Today_Report_detail"),
    path('Today_Report_Edit/<int:pk>/',views.Today_Report_Edit,name="Today_Report_Edit"),
    path('Today_Report_Del/<int:pk>',views.Today_Report_Del,name="Today_Report_Del"),
    

]

acinsite/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from django_summernote import fields as summer_fields
from .models import User,Performance,User_perform,Board,Comment,Reply,Gallery,Gallery_reference, Today_Report

class PostForm(forms.ModelForm):
    board_content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Board
        fields = ('board_title','board_content','board_file')
        widget = { 
            
            'board_content' : forms.Textarea(attrs={'cols':100, 'rows':100}),
        }
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['board_file'].required = False
        self.fields['board_title'].widget.attrs.update({'class':'form-control'})

class Today_Report_Form(forms.ModelForm):
    Today_Report_content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Today_Report
        fields = ('Today_Report_title','Today_Report_content','Today_Report_file')
        widget = {

            'Today_Report_content' : forms.Textarea(attrs={'cols':100, 'rows':100}),
        }
    def __init__(self, *args, **kwargs):
        super(Today_Report_Form, self).__init__(*args, **kwargs)
        self.fields['Today_Report_file'].required = False
        self.fields['Today_Report_title'].widget.attrs.update({'class':'form-control'})

acinsite/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from acinsite.models import *
from acinsite.forms import  *
from django.utils import timezone
from datetime import datetime
#메인
def main(request):
    cur_date = datetime.now().date()
    gal_objs = Gallery.objects.all().order_by('-id')[0:4]
    board_objs = Board.objects.all().order_by('-id')[0:3]
    user_birthday = User.objects.all()
    today_birth_user = User.objects.filter(user_birthday__month=cur_date.month,
                                           user_birthday__day=cur_date.day)
    if today_birth_user:
        today_birth_user = today_birth_user[0]
    context = {
        'cur_date':cur_date,
        'gal_objs':gal_objs,
        'board_objs':board_objs,
        'user_birthday':user_birthday,
        'today_birth_user':today_birth_user
    }
    return render(request,'acinsite/main.html',context)
#로그인
def login(request):
    context = {
        'msg' : '',
    }
    if request.method == "POST":
        user_objs = User.objects.filter(
                        user_number = request.POST.get('user_id'),
                        user_pw = request.POST.get('user_pw')
                    )
        if user_objs:
            request.session['user_id']  = request.POST.get('user_id')
            request.session['user_pk']  = user_objs[0].pk
            request.session['user_name']= user_objs[0].user_name
            return redirect("/")
        else:
            context['msg'] = 'LoginFail'
    return render(request,'acinsite/login.html',context)

#로그아웃
def logout(request):
    if request.session.get('user_id') or request.session.get('user_name'):
        del request.session['user_id']
        del request.session['user_name']
        del request.session['user_pk']


    return redirect('/')
#소개 페이지
def intro(request):
    return render(request,'acinsite/intro.html')
#professor 페이지
def professor(request):
    user = get_object_or_404(User,user_rank=1)
    objects = User_perform.objects.filter(
                    user=user,
                    performance__perf_state=True
                ).order_by('-performance__perf_end')

    print(user)
    print(objects)
    context = {
        'user':user,
        'objects':objects,
    }
    return render(request,'acinsite/professor.html',context)
#멤버 패이지
def member(request):
    users = User.objects.exclude(user_rank=1).order_by('user_rank','user_birthday')
    print(users)
    context = {
        'users':users,
    }
    return render(request,'acinsite/member.html',context)

#프로젝트 메인
def project(request,keyword=None):
    perf_objs = None
    context = {}
    #진행중인 프로젝트
    if keyword == "proceeding":
        perf_objs = Performance.objects.filter(
                    perf_isProfessor=False,
                    perf_state=False
                ).order_by('-perf_start')
        context['type']='proceeding'
    #종료된 프로젝트
    else:
        year_list = []
        perf_objs = Performance.objects.filter(
                    perf_isProfessor=False,
                    perf_state=True
                ).order_by('-perf_end')

        for obj in perf_objs:
            year = obj.perf_end_year
            if not year in year_list:
                year_list.append(year)
        context['year_list']=year_list
        context['type']='finish'

    context['object_list']=perf_objs

    return render(request,'acinsite/project/project_list.html',context)
#ajax 요청 프로젝트
def get_ajax_project(request):
    object_list = None
    if request.POST.get('year') == "all":
        object_list = Performance.objects.filter(
                            perf_isProfessor=False,
                            perf_state=True).order_by('-perf_end')
    else:
        object_list = Performance.objects.filter(
                            perf_isProfessor=False,
                            perf_state=True,
                            perf_end_year=request.POST.get('year')).order_by('-perf_end')
    context = {
        'object_list':object_list
    }
    return render(request,'acinsite/project/ajax_project.html',context)

#프로젝트 생성
def create_project(request):
    if not request.session.get('user_id'):
        return redirect('/login')
    pk = request.GET.get('pk')
    print(pk)
    if request.method == "POST":
        perf_status = False
        start_date = None
        end_date = None
        end_year = None
        if pk:
            print("hello")
            obj = Performance.objects.get(pk=pk)
            obj.delete()

        if request.POST.get('project_status'):
            perf_status=True
        if request.POST.get("start_date") != "":
            start_date = request.POST.get("start_date")
        if request.POST.get("end_date") != "":
            end_date = request.POST.get("end_date")
            end_year = request.POST.get("end_date")[0:4]


        perf_obj = Performance.objects.create(
                        perf_title = request.POST.get('project_title'),
                        perf_type  = request.POST.get('project_type'),
                        perf_content=request.POST.get('project_content'),
                        perf_etc=request.POST.get('project_etc'),
                        perf_host=request.POST.get('project_host'),
                        perf_sponsor=request.POST.get('project_sponso'),
                        perf_state=perf_status,
                        perf_start=start_date,
                        perf_end=end_date,
                        perf_end_year=end_year,
                    )
        if request.FILES.get('file'):
            perf_obj.perf_file=request.FILES.get('file')
        else:
            perf_obj.perf_file=request.POST.get('old_file')
        perf_obj.save(update_fields=['perf_file'])

        for mem in request.POST.getlist('member'):
            if isNumber(mem):
                user = get_object_or_404(User, id=mem)
                User_perform.objects.create(user=user,performance=perf_obj)
            else:
                User_perform.objects.create(other_user=mem,performance=perf_obj)

        return redirect("/project")

    #GET 방식
    context={}

    obj=None

    if pk:
        obj = get_object_or_404(Performance,pk=pk)
        context['obj']=obj


    users = User.objects.all().order_by('user_rank','user_birthday')
    context['users']=users
    return render(request,'acinsite/project/create_project.html',context)

def modify_list(request):
    # GET
    if not request.session.get('user_id'):
        return redirect('/login')
    if request.method == "GET":
        object_list = Performance.objects.exclude(perf_isProfessor=True).order_by('perf_state')
        print(object_list)
        context = {
            'object_list':object_list,
        }
        return render(request,'acinsite/project/modify_list.html',context)


def delete_project(request,pk):
    obj = get_object_or_404(Performance,pk=pk)
    obj.delete()
    return redirect("/project/modify/list/")

def one_page_count(objs,page):
    total_row = 12
    start = total_row * (page-1)
    end   = total_row + start


    return objs.count(),objs[start:end]

def gallery(request):
    context = {}
    object_list = None
    total_count = None
    page = int(request.GET.get('page'))
    if request.GET.get('keyword') == "modify":
        user_id = request.session.get('user_id')
        user=get_object_or_404(User,user_number=user_id)
        objs=Gallery.objects.filter(user=user)
        total_count,object_list = one_page_count(objs,page)
        context['keyword'] = "modify"

    else:
        objs = Gallery.objects.all().order_by('-id')
        total_count,object_list = one_page_count(objs,page)


    context['object_list'] = object_list
    context['page'] = page
    context['total_count'] = total_count
    return render(request,'acinsite/gallery/gallery.html',context)

#갤러리 쓰기
def write_gallery(request):
    if not request.session.get('user_id'):
        return redirect('/login')
    context = {}
    pk = request.GET.get('pk')
    if request.method == "POST":
        atch_file = None
        files = []
        #기존 테이블 삭제
        if pk:
            Gallery.objects.get(pk=pk).delete()
        user = get_object_or_404(User,user_number=request.session.get('user_id'))
        if request.FILES.get('atchdFile'):
            atch_file = request.FILES.get('atchdFile')
        elif request.POST.get('atchdFile'):
            atch_file = request.POST.get('atchdFile')

        gal_obj = Gallery.objects.create(
                        user=user,
                        gal_title=request.POST.get('title'),
                        gal_file =atch_file,
                    )

        if request.FILES.getlist('file'):
            files=request.FILES.getlist('file')
        if request.POST.getlist('file-mfy'):
            files+=request.POST.getlist('file-mfy')


        for file in files:
            Gallery_reference.objects.create(
                gallery=gal_obj,
                gal_photo=file
            )
        return HttpResponse("성공")
    if pk:
        obj = get_object_or_404(Gallery,pk=pk)
        context['obj'] = obj

    return render(request,'acinsite/gallery/write_gallery.html',context)
def detail_gallery(request,pk):

    obj = get_object_or_404(Gallery,pk=pk)
    obj.gal_hits = obj.gal_hits + 1
    obj.save(update_fields=['gal_hits'])
    context = {
        'obj':obj,
    }
    return render(request,'acinsite/gallery/detail_gallery.html',context)
def delete_gallery(request,pk):
    obj = get_object_or_404(Gallery,pk=pk)
    obj.delete()
    return redirect('/gallery?page=1')
#숫자 이냐?
def isNumber(number):
    try:
        int(number)
        return True
    except ValueError:
        return False

#mypage
def mypage(request):
    user_id = request.session.get('user_id')
    user = User.objects.get(user_number=user_id)
    print(user)
    context = {
        'user':user,
    }
    return render(request,'acinsite/mypage/member_info.html',context)
def Viewboard(request):
    vb = Board.objects.all().order_by('-pk')

acinsite/templates/acinsite/board/Boarddetail.html
{% extends 'base.html' %}
{% load static %}
{% block depth %}
    <div class="depth">
        <span>HOME</span>
        <span>></span>
        <span>BOARD</span>
        <span>></span>
        <span style="color: rgb(12,92,161);">DETAIL</span>
    </div>
{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/side-bar.css' %}" />

<style>
    .content span{
        display: inline-block;
        margin-left:30px;
    }
    #b-info .info-val{
        color:#b2b2a2;
    }

    #list-btn{
        display: inline-block;
        width:111px;
        height: 36px;
        border: 1px solid #bfbfbf;
        font-size: 20px;
        text-align: center;
        line-height: 36px;
        color:black;
        font-weight: 10px;
        cursor: pointer;
        text-decoration: none;
    }
    #d-btn a{
        display: inline-block;
        margin-right:19px;
        color:#bfbfbf;
    }
</style>
<div class="container-box">
    <div class="nav">
        <div class="nav-header">
           <p>Board</p>
        </div>
        <ul class="nav-list">
            <li>
                <a href="{% url 'Main:Viewboard' %}">
                    <p class="text-center" style="margin-top:10px;">
                        <span>Notice</span>
                    </p>
            </li>
            {% if request.session.user_id %}
            <li>
                <a href="{% url 'Main:Today_Report_Board' %}">
                    <p class="text-center" style="margin-top:10px;">

                        <span>일일보고</span>
                    </p>
                </a>
            </li>
            {% endif %}      
            <li>

                <a href="/gallery?page=1">
                    <p class="text-center" style="margin-top:10px;">
                        <span>Gallery</span>
                    </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="content">
        <hr style="border:2px solid #555555;">
        <!--title-->
        <h3 style="margin-left:30px;">{{de.board_title}}</h3>
        <hr style="border-color:#bfbfbf;">
        <div id="b-info">
            <span><b>글쓴이</b></span>
            <span class="info-val">{{de.user}}</span>
            <span style="color:#b2b2a2;">|</span>
            <span><b>작성일</b></span>
            <span class="info-val">{{de.board_date}}</span>
            <span style="color:#b2b2a2;">|</span>
            <span><b>조회수</b></span>
            <span class="info-val">{{de.board_hits}}</span>
        </div>
        <hr style="border-color:#bfbfbf;">
        <div style="margin-left:30px;">
            <p>첨부파일</p>
            {% if de.board_file %}
                <a href="/media/{{de.board_file}}" download="download">{{de.board_file}}</a>
            {% else %}
                <p style="color:#bfbfbf;">첨부파일이 없습니다.</p>
            {% endif %}
        </div>
        <hr style="border-color:#bfbfbf;">
        <p style="margin-left:30px;">
            {{de.board_content|safe}}
        </p>
        <hr style="border-color:#bfbfbf;">
        <div class="text-right">
            <div id="d-btn">


                {% if request.session.user_name == de.user.user_name%}

                    <a style="cursor: pointer; color:gray;" onclick="modify_and_delete('mod');">수정</a>
                    <a style="cursor: pointer; color:gray;" onclick="modify_and_delete('del');">삭제</a>
                {% endif %}

            </div>

            <a id="list-btn" href="{% url 'Main:Viewboard' %}">목록</a>
        </div>
        <hr style="border:2px solid #555555;">
        <div id="prev-text">
            <span>
                <b>이전글</b>
            </span>
            <span class="info-val">|</span>
            <span>
                {% if prev_board %}
                    <a href="{% url 'Main:Boarddetail' prev_board.pk %}">{{prev_board.board_title}}</a>
                {% else %}
                    이전글이 없습니다
                {% endif %}
            </span>
        </div>
        <hr style="border-color:#bfbfbf;">
        <div id="next-text">
            <span><b>다음글</b></span>
            <span class="info-val">|</span>
            <span>
                {% if next_board %}
                   <a href="{% url 'Main:Boarddetail' next_board.pk %}">{{next_board.board_title}}</a>

                {% else %}
                    다음글이 없습니다
                {% endif %}
            </span>
        </div>
        <hr style="border-color:#bfbfbf;">
    </div>
    <script>
        function modify_and_delete(type,pk){
            //수정
            if(type == "mod"){
                window.location.href="{% url 'Main:Editboard' de.pk %}";
            }
            //삭제
            else if(type == "del"){
                if(confirm("삭제하시겠습니까?")){
                    window.location.href="{% url 'Main:Deleteboard' de.pk %}";
                }


            }
        }

    </script>
{% endblock %}

acinsite/templates/acinsite/board/Editboard.html
{% extends 'acinsite/board/Writeboard.html' %}
{% load static %}
{% block depth %}
<div class="depth">
        <span>HOME</span>
        <span>></span>
        <span>BOARD</span>
        <span>></span>
        <span style="color: rgb(12,92,161);">Edit</span>
    </div>
{% endblock %}
{% block content %}
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
<!--외부 css 파일-->
<link rel="stylesheet" type="text/css" href="{% static 'css/side-bar.css' %}" />
<div class="container-box">
    <div class="nav">
        <div class="nav-header">
           <p>Board</p>
        </div>
        <ul class="nav-list">
            <li>
                <a href="{% url 'Main:Viewboard' %}">

                    <p class="text-center" style="margin-top:10px;">
                        <span>Notice</span>
                    </p>
                </a>
            </li>
            {% if request.session.user_id %}
            <li>
                <a href="{% url 'Main:Today_Report_Board' %}">
                    <p class="text-center" style="margin-top:10px;">

                        <span>일일보고</span>
                    </p>
                </a>
            </li>
            {% endif %}     
            <li>
                <a href="/gallery?page=1">
                    <p class="text-center" style="margin-top:10px;">
                    <span>Gallery</span>
                    </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="content">

<form action="{% url 'Main:Editboard' eb.pk  %}" method="POST" id="formId" value="" enctype="multipart/form-data">
    {% csrf_token %}

        <p>제목:</p>
        <input type='text' id='board_title' class="form-control" name='board_title' value="{{ eb.board_title }}"><br>
        <p>첨부파일:</p>
        {% if eb.board_file %}
            <span style="color:gray;">Currently:</span>
            <a href="/media/{{eb.board_file}}" download="download">{{eb.board_file}}</a>
            <input type="checkbox" id="clear" name="clear">
            <label for="clear">clear</label>
            <br>
        {% endif %}
        <span style="color:gray;">Change:</span>
        <input type="file" style="display: inline;" name="file">
        <br>

        <p>내용:</p>
        <!-- <input type='text' id='board_content' name='board_content'  value="{{ eb.board_content }}"> -->
        <div id="summernote">{{ eb.board_content|safe}}</div>
        <input type="hidden" id="final_Board_content" name="board_content">
        <input type="button" value="수정" onclick="submit_click();">


</form>
<script>
    function submit_click() {
        boardcontent();
        alert("수정되었습니다.");

    }
 //썸머노트
$(document).ready(function() {
  $('#summernote').summernote();
});

$('#summernote').summernote({
  height: 300,
  minHeight: null,
  maxHeight: null,
  focus: true
});

function boardcontent(){
    var markupStr = $('#summernote').summernote('code');
    $("#final_Board_content").val(markupStr);
    $("#formId").submit();
  }

// 글올리기
function oncheckfile(){
        $("#board_submit").css('display','none');
        $("#upload_comment").css('display','block');
    }

 </script>
 <script>

        $(".container-box").height($(window).height()-320);
        $(window).resize(function() {
            $(".container-box").height($(window).height()-320);
         });
    </script>

{% endblock %}

acinsite/templates/acinsite/board/Viewboard.html
{% extends 'base.html' %}
{% load static %}
{% block depth %}
<div class="depth">
        <span>HOME</span>
        <span>></span>
        <span>BOARD</span>
        <span>></span>
        <span style="color: rgb(12,92,161);">VIEW</span>
    </div>
{% endblock %}
{% block content %}

    <!--외부 css 파일-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/side-bar.css' %}" />

    <div class="container-box">
        <div class="nav">
            <div class="nav-header">
               <p>Board</p>
            </div>
            <ul class="nav-list">
                <li>
                    <a href="{% url 'Main:Viewboard' %}">
                        <p class="text-center" style="margin-top:10px;">

                            <span>Notice</span>
                        </p>
                    </a>
                </li>
                {% if request.session.user_id %}
                <li>
                    <a href="{% url 'Main:Today_Report_Board' %}">
                        <p class="text-center" style="margin-top:10px;">

                            <span>일일보고</span>
                        </p>
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="/gallery?page=1">
                        <p class="text-center" style="margin-top:10px;">
                            <span>Gallery</span>
                        </p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content">
            <h1>Notice</h1>
            <h3>ACIN 연구실에 오신것을 환영합니다.</h3>
            {% block board %}
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>순번</th>
                        <th>제목</th>
                        <th>작성자</th>
                        <th>작성일</th>
                        <th>조회수</th>
                    </tr>
                </thead>
                {% for vb in vb %}
                <tbody>
                    <tr>
                        <td>{{ forloop.revcounter }}</td>
                        <td><a href="{% url 'Main:Boarddetail' vb.pk %}">{{ vb.board_title }}</a></td>
                        <td>{{ vb.user }}</td>
                        <td>{{ vb.board_date|date:"Y/m/d" }}</td>
                        <td>{{ vb.board_hits }}</td>
                    </tr>
                </tbody>

            {% endfor %}

            {% endblock %}
        </table>
            <a href="{% url 'Main:Writeboard' %}"class="btn btn-default pull-right">글쓰기</a>
        </div>
    </div>
    <hr>
    <script>

        $(".container-box").height($(window).height()-320);
        $(window).resize(function() {
            $(".container-box").height($(window).height()-320);
         });
    </script>
{% endblock %}

acinsite/templates/acinsite/board/Writeboard.html
{% extends 'base.html' %}
{% load static %}
{% block depth %}
<div class="depth">
        <span>HOME</span>
        <span>></span>
        <span>BOARD</span>
        <span>></span>
        <span style="color: rgb(12,92,161);">WRITE</span>
    </div>
{% endblock %}
{% block content %}
<!-- 썸머노트 -->
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
<style>
   ul li{
       list-style: none;
   }
</style>
<!--외부 css 파일-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/side-bar.css' %}" />


    <div class="container-box">
        <div class="nav">
            <div class="nav-header">
               <p>Board</p>
            </div>
            <ul class="nav-list">
                <li>
                    <a href="{% url 'Main:Viewboard' %}">
                        <p class="text-center" style="margin-top:10px;">
                            <span>Notice</span>
                        </p>
                    </a>
                </li>
                {% if request.session.user_id %}
                <li>
                    <a href="{% url 'Main:Today_Report_Board' %}">
                        <p class="text-center" style="margin-top:10px;">

                            <span>일일보고</span>
                        </p>
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="/gallery?page=1">
                        <p class="text-center" style="margin-top:10px;">
                            <span>Gallery</span>
                        </p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content">
            {% block board %}
            <form action="{% url 'Main:Writeboard' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                제목:<br> {{ form.board_title }}<br>
                {{ form.board_file }}
                    <div id="summernote"></div>
                    <input type="hidden" id=final_Board_content name="board_content">
                    <button id=board_submit name=board_submit class="btn btn-default pull-right" onclick="oncheckfile();">작성하기</button>

            {% endblock %}

                    <p id=upload_comment name=upload_comment style="display:none;">업로드 중 ....<p>
            </form>
            </div>
            <hr><br>
<script>
//썸머노트
$(document).ready(function() {
  $('#summernote').summernote();
});

$('#summernote').summernote({
  height: 300,
  minHeight: null,
  maxHeight: null,
  focus: true,
  placeholder:"내용을 입력하세요."
});

function boardcontent(){
    var markupStr = $('#summernote').summernote('code');
    console.log(markupStr);
    $("#final_Board_content").val(markupStr);
    document.board_view.submit();
  }

// 글올리기
function oncheckfile(){

    boardcontent();
     $("#board_submit").css('display','none');
    $("#upload_comment").css('display','block');
    }

</script>
<script>

        $(".container-box").height($(window).height()-320);
        $(window).resize(function() {
            $(".container-box").height($(window).height()-320);
         });
    </script>
{% endblock %}