acin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('acinsite.urls')),
    path('document/', include('document.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acinsite/urls.py
from django.urls import path
from acinsite import views
app_name='Main'

urlpatterns=[
    path('',views.main, name="main"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    path('intro/',views.intro,name="intro"),
    path('professor/',views.professor,name="professor"),
    path('member/',views.member,name="member"),
    path('project/create/',views.create_project,name="create-project"),
    path('project/delete/<pk>/',views.delete_project,name="delete-project"),
    path('project/modify/list/',views.modify_list,name="modify-list"),
    path('project/ajax/',views.get_ajax_project,name="ajax-project"),
    path('project/',views.project,name="project"),
    path('project/<keyword>/',views.project,name="project"),
    path('gallery/write/',views.write_gallery,name="write-gallery"),
    path('gallery/',views.gallery,name="gallery"),
    path('gallery/detail/<int:pk>/',views.detail_gallery,name="detail-gallery"),
    path('gallery/delete/<int:pk>/',views.delete_gallery,name="delete-gallery"),
    #MYPAGE
    path('mypage/',views.mypage,name="mypage"),
    
    #게시판
    path('board/Viewboard/',views.Viewboard,name="Viewboard"),
    path('board/Writeboard/',views.Writeboard,name="Writeboard"),
    path('board/Viewboard/Boarddetail/<int:pk>',views.Boarddetail,name="Boarddetail"),
    path('board/Viewboard/Boarddetail/Deleteboard/<int:pk>',views.Deleteboard, name="Deleteboard"),
    path('board/Viewboard/Boarddetail/Editboard/<int:pk>',views.Editboard, name="Editboard"),

    #일일보고
    path('Today_Report_Today_Report_Board',views.Today_Report_Board, name="Today_Report_Board"),
    path('Write_Today_Report', views.Write_Today_Report,name="Write_Today_Report"),
    path('Today_Report_detail/<int:pk>/',views.Today_Report_detail,name="Today_Report_detail"),
    path('Today_Report_Edit/<int:pk>/',views.Today_Report_Edit,name="Today_Report_Edit"),
    path('Today_Report_Del/<int:pk>',views.Today_Report_Del,name="Today_Report_Del"),
    

]

acinsite/models.py
from django.db import models
#유저
class User(models.Model):
    user_number = models.CharField(max_length=20,null=True,blank=True, verbose_name="학번")
    user_pw = models.CharField(max_length=20 ,null=True,blank=True, verbose_name="비밀번호")
    user_name = models.CharField(max_length=20, null=True,blank=True, verbose_name="이름")
    user_email = models.EmailField(null=True,blank=True,verbose_name="이메일")
    user_major = models.CharField(max_length=20, null=True,blank=True, verbose_name="학과")
    user_profile = models.ImageField(blank=True, verbose_name="프로필 사진")
    user_birthday = models.DateField(null=True,blank=True, verbose_name="생년월일")
    user_phone = models.CharField(max_length=11,null=True,blank=True,verbose_name="핸드폰번호")
    user_ranklist = (('1','교수'),('2','팀장'),('3','팀원'))
    user_rank = models.CharField(max_length=10, choices=user_ranklist, null=True,blank=True,verbose_name="직책")
    user_interest  = models.CharField(max_length=40,null=True,blank=True,verbose_name="관심분야1")
    user_interest2 = models.CharField(max_length=40,null=True,blank=True,verbose_name="관심분야2")
    user_interest3 = models.CharField(max_length=40,null=True,blank=True,verbose_name="관심분야3")
    user_highschool = models.CharField(max_length=20, null=True,blank=True,verbose_name="출신 고등학교")
    user_highschool_date = models.DateField(null=True,blank=True, verbose_name="고등학교 졸업일")
    user_university = models.CharField(max_length=20,null=True,blank=True, verbose_name="출신 대학교")
    user_university_date = models.DateField(null=True,blank=True,verbose_name='대학 졸업일')
    user_master = models.CharField(max_length=20,null=True,blank=True,verbose_name="석사")
    user_master_date = models.DateField(null=True,blank=True,verbose_name="석사임명 날짜")
    user_doctor = models.CharField(max_length=20,null=True,blank=True,verbose_name="박사")
    user_doctor_date = models.DateField(null=True,blank=True,verbose_name="박사임명 날짜")

    def __str__(self):
        return self.user_name

# 프로젝트
class Performance(models.Model):
    perf_title = models.CharField(max_length=200,null=True,blank=True, verbose_name="프로젝트 제목")
    perf_typelist =(('1','프로젝트'),('2','논문'),('3','지적재산권'))
    perf_type = models.CharField(max_length=10,choices=perf_typelist,null=True,blank=True,verbose_name="프로젝트 종류")
    perf_content = models.TextField(max_length=200,null=True,blank=True, verbose_name="내용")
    perf_etc = models.TextField(max_length=100,null=True,blank=True, verbose_name="비고")
    perf_host = models.CharField(max_length=20,null=True,blank=True , verbose_name="주관")
    perf_sponsor = models.CharField(max_length=20,null=True,blank=True, verbose_name="발주")
    perf_state = models.BooleanField(default=False, verbose_name="상태")
    perf_start = models.DateField(null=True,blank=True, verbose_name="프로젝트 시작일")
    perf_end = models.DateField(null=True,blank=True, verbose_name="프로젝트 종료일")
    perf_end_year = models.CharField(max_length=4,null=True,blank=True,verbose_name="종료연도")
    perf_file = models.FileField(null=True,blank=True, verbose_name="파일",upload_to="project/")
    perf_isProfessor = models.BooleanField(default=False, verbose_name="교수님 프로젝트")


    def __str__(self):
        return self.perf_title
# 유저와 프로젝트 연결
class User_perform(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE ,null=True,blank=False)
    other_user = models.CharField(max_length=20 , null=True, blank=True)
    performance = models.ForeignKey(Performance,on_delete=models.CASCADE,related_name="perf",null=True,blank=False)


#게시판
class Board(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=False,verbose_name="작성자")
    board_title = models.CharField(max_length=100,null=True,blank=False,verbose_name="게시판 제목")
    board_content = models.TextField(max_length=500,null=True,blank=False,verbose_name="내용")
    board_date = models.DateTimeField(null=True,blank=False, verbose_name="작성일")
    board_hits = models.IntegerField(default=0,verbose_name="조회수")
    board_file = models.FileField(null=True,blank=True, verbose_name="파일")

    def __str__(self):
        return self.board_title
#댓글
class Comment(models.Model):
    board = models.ForeignKey(Board,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=False)
    comment_content = models.TextField(max_length=30,null=True,blank=True,verbose_name="댓글")
    comment_date = models.DateTimeField(null=True,blank=False, verbose_name="작성시간")

    def __str__(self):
        return self.comment_content
#대댓글
class Reply(models.Model):
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=False)
    reply_content = models.TextField(null=True,blank=True,verbose_name="대댓글")
    reply_date = models.DateTimeField(null=True,blank=False,verbose_name="대댓글 작성시간")

    def __str__(self):
        return self.reply_content

def gallery_img_upload(instance, file):

    return "gallery/".format(instance.gal_title,file)

def gal_ref_img_upload(instance,file):
    return "gallery/{}/{}".format(instance.gallery.id,file)


#겔러리
class Gallery(models.Model):
    user = models.ForeignKey(User,null=True,blank=False, on_delete=models.CASCADE)
    gal_title = models.CharField(max_length=100,null=True,blank=False,verbose_name="제목")
    gal_date = models.DateField(null=True,blank=False,verbose_name="작성일",auto_now_add=True)
    gal_hits = models.IntegerField(default=0, verbose_name="조회수")
    gal_file = models.FileField(null=True,blank=True,upload_to=gallery_img_upload,verbose_name="파일")
    def __str__(self):
        return self.gal_title



#겔러리 여러사진 등록
class Gallery_reference(models.Model):
    gallery = models.ForeignKey(Gallery,related_name="galleryref",on_delete=models.CASCADE,)
    gal_photo = models.ImageField(null=True,blank=True,verbose_name="사진",upload_to=gal_ref_img_upload)


#일일보고
class Today_Report(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=False,verbose_name="작성자")
    Today_Report_title = models.CharField(max_length=100,null=True,blank=False,verbose_name="게시판 제목")
    Today_Report_content = models.TextField(max_length=500,null=True,blank=False,verbose_name="내용")
    Today_Report_date = models.DateTimeField(null=True,blank=False, verbose_name="작성일")
    Today_Report_hits = models.IntegerField(default=0,verbose_name="조회수")
    Today_Report_file = models.FileField(null=True,blank=True, verbose_name="파일")

    def __str__(self):
        return self.Today_Report_title

acinsite/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from django_summernote import fields as summer_fields
from .models import User,Performance,User_perform,Board,Comment,Reply,Gallery,Gallery_reference, Today_Report

class PostForm(forms.ModelForm):
    board_content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Board
        fields = ('board_title','board_content','board_file')
        widget = { 
            
            'board_content' : forms.Textarea(attrs={'cols':100, 'rows':100}),
        }
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['board_file'].required = False
        self.fields['board_title'].widget.attrs.update({'class':'form-control'})

class Today_Report_Form(forms.ModelForm):
    Today_Report_content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Today_Report
        fields = ('Today_Report_title','Today_Report_content','Today_Report_file')
        widget = {

            'Today_Report_content' : forms.Textarea(attrs={'cols':100, 'rows':100}),
        }
    def __init__(self, *args, **kwargs):
        super(Today_Report_Form, self).__init__(*args, **kwargs)
        self.fields['Today_Report_file'].required = False
        self.fields['Today_Report_title'].widget.attrs.update({'class':'form-control'})

acinsite/templates/acinsite/intro.html
{% extends 'base.html' %}
{% load static %}
{% block depth %}
    <div class="depth">
    <span>HOME</span>
    <span>></span>
    <span style="color: rgb(12,92,161);">INTRODUCTION</span>
    </div>
{% endblock %}
{% block content %}
    <style>
       .intro-section{
           width:1000px;
           height:300px;
           margin:0px auto;
       }
      hr{
          clear: both;
      }
    </style>
     
    <div class="intro-section">
        <h3>BIG DATA</h3>
        <div class="row">
            <p class="col-md-6">
            온라인 정보를 활용한 식당 사용자 패턴 분석, 빅데이터 분석을 이용한 <br>
            식당 지능화 시스템 논문으로 한국지능시스템학회 학술대회 우수논문상 
            수상
            </p>
            <p class="col-md-6">
                <img class="col-md-12" src="{% static 'img/good.jpg' %}">
            </p>
        </div>
    </div>
    <hr>
    <div class="intro-section">
        <h3>WEB</h3>
        <div class="row">
            <p class="col-md-6">
                HTML, JAVASCRIPT, DJANGO, AJAX, PYTHON을 활용한<br> 인사 담당 시스템을 구축중에 있다.
            </p>
            <p class="col-md-6">
                <img class="col-md-12" src="{% static 'img/makehomepage.png' %}">
            </p>
        </div>
    </div>
    <hr>
    <div class="intro-section">
        <h3>APP</h3>
        <div class="row">
            <p class="col-md-6">
                작업예정 
            </p>
            <p class="col-md-6">
                <img class="col-md-12" src="{% static 'img/dog.jpg' %}">
            </p>
        </div>
    </div>

{% endblock %}

acinsite/templates/acinsite/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--부트스트랩-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    
    <!--제이쿼리-->
    <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <style>
        #error_box{
            width:40%;
            height:70px;
            margin-left:35%;
            padding-top:17px;
            color:rgb(217,87,103);
            background-color:rgb(244,204,209);
        }
        #login-form{
            margin-top:100px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2" id="login-form">
           {% if msg == 'LoginFail' %}
                <div id="error_box">
                    <p id="error_box_text" class="text-center"><i class="glyphicon glyphicon-alert"></i>
                        아이디 또는 비밀번호가 <br/>일치하지 않습니다.</p>
                </div>
                <script>
                    setTimeout(function(){
                        $("#error_box").hide(200);
                    },3000);
                </script>
            {% endif %}    
            <form action="{% url 'Main:login' %}" method="POST">
                {% csrf_token %}
                <label>아이디</label><br>
                <input type="text" class="form-control" name="user_id" id="user-id" placeholder="아이디">
                <p id="id-error-text" style="color:red; display: none;">아이디를 입력해주세요.</p>
                <label>비밀번호</label><br>
                <input type="password" class="form-control" name="user_pw" id="user-pw" placeholder="비밀번호">
                <p id="pw-error-text" style="color:red; display: none;">비밀번호를 입력해주세요.</p><br>
                <input type="submit" class="form-control btn btn-primary" value="로그인">
            </form>
        </div>
    </div> 
    <script>
        $("#user-id").focusout(function(){
            if($(this).val() == ""){
                $("#id-error-text").css("display","block");
                $(this).css("border-color","red");
            }else{
                $("#id-error-text").css("display","none");
                $(this).css("border-color","rgb(204,204,204)");
            }
        });
        $("#user-pw").focusout(function(){
            if($(this).val() == ""){
                $("#pw-error-text").css("display","block");
                $(this).css("border-color","red");
            }else{
                $("#pw-error-text").css("display","none");
                $(this).css("border-color","rgb(204,204,204)");
            }
        });
    </script>
</body>
</html>

acinsite/templates/acinsite/main.html
{% extends 'base.html' %}
{% load static %}
{% block slider %}
<link href='{% static "packages/core/main.css" %}' rel='stylesheet' />
<link href='{% static "packages/daygrid/main.css" %}' rel='stylesheet' />
<link href='{% static "packages/timegrid/main.css" %}' rel='stylesheet' />
<link href='{% static "packages/list/main.css" %}' rel='stylesheet' />
<script src='{% static "packages/core/main.js" %}'></script>
<script src='{% static "packages/core/locales-all.js" %}'></script>
<script src='{% static "packages/interaction/main.js" %}'></script>
<script src='{% static "packages/daygrid/main.js" %}'></script>
<script src='{% static "packages/timegrid/main.js" %}'></script>
<script src='{% static "packages/list/main.js" %}'></script>


<style>
    body {
    margin: 0;
    padding: 0;
    font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
    font-size: 14px;
  }
  ul{
    list-style: none;
  }
  #top {
    background: #eee;
    border-bottom: 1px solid #ddd;
    padding: 0 10px;
    line-height: 40px;
    font-size: 12px;
  }

  #calendar {
    max-width: 723px;
    margin-top:20px;
    padding: 0 10px;
  }



  .carousel img{
     width:100%;
     
  }
  
  #board-box{
      width:723px;
      height:200px;
      position: relative;
      border-top:1px solid blue;
      margin-left:80px;
   
  }
  
  #new-board-list{
      width: 325px;
      position:absolute;
      right:0px;
      top:24px;
  }
  #notice{
    position: relative;
    
  }
  #main-notice{
    margin-left:80px;
  }
  #main-gallery{
    position: absolute;
    right: 80px;
    top:-9px;
  }
  #main-intro{
    margin-left:80px;
  }
  #main-gallery .img-box{
    width:200px;
    height:200px;
    
    cursor: pointer;
    margin-top:20px;
    overflow: hidden;
  }
  .intro-box{
    list-style: none;
    width:700px;
    border-top:1px solid blue;
  }
  .intro-box li{
    width:220px;
    height: 149px;
    float: left;
    background:rgb(245,245,245); 
  }
  .intro-box .center-child{
    margin:0 20px;
  }
  .intro-box li p{
    word-wrap: break-word;
  }
  .item{
    width:auto;
    height: 600px;
    background-repeat: no-repeat;
     
    background-position: center;
  }
  #slider1{
    background-image: url("{% static 'img/cb.jpg' %}");
    

  }
  #slider2{
    background-image: url("{% static 'img/cb2.png' %}");
  }
  #slider3{
    background-image: url("{% static 'img/gkrghl6.jpg' %}");
    
  }
  #slider4{
    background-image: url("{% static 'img/meeting.jpg' %}");
    
    
  }
  #board-icon-box{
    width:80px;
    height:130px;
    border: 1px solid rgb(221,221,221);
    margin-left:30px;
    margin-top:20px;
    float: left;
  }
  .new-board{
    width:360px;
    margin-top:30px;
    padding-left:135px;
    
  }
  
</style>
<div id="carousel-example-generic" class="carousel slide" style="clear:both;"  data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active" id="slider1"></div>
    <div class="item" id="slider2"></div>
    <div class="item" id="slider3"></div>
    <div class="item" id="slider4"></div>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>
  <div>
    
  </div>
{% endblock %}

{% block content %}

      <script>
        date_list = []
      </script>
      {% for user in user_birthday %}
          <script>
            var title = "";
            if ("{{user.user_rank}}" == "1"){
                title = "교수님 생일";
            }else{
                title ="{{user.user_name}} 생일";
            }
            date_list.push({
              'title':title,
              'start':"{{cur_date|date:'Y'}}-{{user.user_birthday|date:'m-d'}}"
            })
          </script>
      {% endfor %}

      <div id="notice">
        <div id="main-notice">
          <h4 style="margin-left:80px;">
            Board
          
            <i class="glyphicon glyphicon-plus" style="margin-left:650px; cursor: pointer;" onclick="extends_list('board');"></i>
            
          </h4>
          
          <div id="board-box">
                
              <!--최신순 게시글-->
              <div id="board-icon-box">
                <div class="text-center" style="line-height: 50px;">
                  <img src="{% static 'img/notice_icon.png' %}">
                </div>
                <div class="board-date text-center">
                  {% if today_birth_user %}
                    <span style="color:black;"><b>{{cur_date|date:"m.d"}}</b></span><br>
                    <span>{{cur_date|date:"Y"}}</span>
                  {% else %}
                    {% if board_objs %}
                      <span style="color:black;"><b>{{board_objs.0.board_date|date:"m.d"}}</b></span><br>
                      <span>{{board_objs.0.board_date|date:"Y"}}</span>
                    {% endif %}  
                  {% endif %}  
                </div>
              </div>
              <div class="new-board">
                {% if today_birth_user %}
                  <p style="font-size:20px;">
                        
                      <a style="color:black;">
                        {{today_birth_user.user_name}}님 <br>생일축하합니다.      
                      </a>
                      
                  </p>
                {% else %}
                    {% if board_objs %}  
                        <p style="font-size:20px;">
                      
                          <a href="{% url 'Main:Boarddetail' board_objs.0.pk %}" style="color:black;">
                            {{board_objs.0.board_title}}
                          </a>
                          
                        </p>
                        <p style="color:#696969;">{{board_objs.0.board_date|date:"Y-m-d"}}</p>
                      {% endif %}
                {% endif %}  
              </div>
              
              <ul id="new-board-list">
              {% for obj in board_objs %}
              
                    <li>
                      <p>
                        <b style="color:#696969;">
                          <span style="color:rgb(12,92,161); font-size:15px;">.</span>
                          <a href="{% url 'Main:Boarddetail' obj.pk %}" style="color:#696969;">
                            {{obj.board_title}}
                          </a>
                        </b>
                      </p>
                      <p style="color:#696969; margin-left:10px;">{{obj.board_date|date:"Y-m-d"}}</p>
                    </li>
                   
                
              {% endfor %}  
              </ol>
            </ul>
        </div>
        <div id="main-gallery">
            <h4>
              Gallery
              <i class="glyphicon glyphicon-plus" style="margin-left:119px; cursor: pointer;" onclick="extends_list('gallery')"></i>
            </h4>
           
            {% for obj in gal_objs %}
              <div class="img-box" onclick="gallery_click({{obj.pk}});">
                  <img width="100%" height="180" src="/media/{{obj.galleryref.first.gal_photo}}">
                  <p>{{obj.gal_title}}</p>
              </div>
              
            {% endfor %}  
        </div>
        <h4 style="margin-left:80px; margin-top:50px;">
          Schedule
          
        </h4>
        <div id="main-intro" style="max-width:723px; border-top:1px solid blue;">
          <div id='calendar'></div>
        </div>
        </div>
        </div>
      <script>
        console.log(date_list);
        function gallery_click(pk){
          window.location.href="/gallery/detail/"+pk+"/";
        }
      //  $('.carousel').carousel({
      //   interval: 2000
      //  });
      $('.carousel').carousel();

      document.addEventListener('DOMContentLoaded', function() {
    var initialLocaleCode = 'ko';
    var localeSelectorEl = document.getElementById('locale-selector');
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list' ],
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
      },
      defaultDate: '{{cur_date|date:"Y-m-d"}}',
      locale: initialLocaleCode,
      buttonIcons: false, // show the prev/next text
      weekNumbers: true,
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: date_list
    });
      
  
    calendar.render();

    // build the locale selector's options
    calendar.getAvailableLocaleCodes().forEach(function(localeCode) {
      var optionEl = document.createElement('option');
      optionEl.value = localeCode;
      optionEl.selected = localeCode == initialLocaleCode;
      optionEl.innerText = localeCode;
      localeSelectorEl.appendChild(optionEl);
    });

    // when the selected option changes, dynamically change the calendar option
    localeSelectorEl.addEventListener('change', function() {
      if (this.value) {
        calendar.setOption('locale', this.value);
      }
    });

  });


  function extends_list(type){
    if(type == "board"){
      window.location.href="{% url 'Main:Viewboard' %}";
    }else{
      window.location.href="/gallery/?page=1";
    }
  }
      </script>
{% endblock %}

acinsite/templates/acinsite/professor.html
{% extends 'base.html' %}
{% load static %}
{% block depth %}


<div class="depth">
    <span>HOME</span>
    <span>></span>
    <span style="color: rgb(12,92,161);">PROFESSOR</span>
</div>
{% endblock %}
{% block content %}
    <!--외부 css 파일-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/side-bar.css' %}" />
    
    <style>
        .pro-content{
            width:600px;
            height: 260px;
            background: rgb(128,148,167);
            margin-left:276px;
            padding-top:37px;
        }
        .inner-box{
            width:436px;
            height: 185px;
            border:1px solid white;
            margin:0 auto;
            
        }
        .inner-box p{
            margin-top:24px;
        }
        .inner-box span{
            font-size: 17px;
        }
    </style>    
    <div class="container-box">
        <div class="nav">
            <div class="nav-header">
               <p>Professor</p>
            </div>
            <ul class="nav-list">
                <li>
                    <a href="{% url 'Main:professor' %}">
                        <p class="text-center" style="margin-top:10px;">
                            <span>Professor</span>
                        </p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content">
            <h4>Professor</h4>
            <hr>
            <div class="profile">
                <div class="profile-img">
                    <img width="200"  height="224" src="/media/{{user.user_profile}}">
                    <h3 style="margin-left:28px;">{{user.user_name}} 교수</h3>
                </div>
                <div class="pro-content">
                    <div class="inner-box">
                        
                        <p>
                            <span style="margin-left:40px; color:rgb(212,228,237);">직위</span> 
                            <span style="margin-left:57px; color:white;">{{user.get_user_rank_display}}</span>
                        </p>
                        <hr width="400" style="margin: 0 auto; border-color:rgb(144,163,180);">
                        <p>
                            <span style="margin-left:40px; color:rgb(212,228,237);">전화번호</span> 
                            <span style="margin-left:29px; color:white;">8496</span>
                        </p>
                        <hr width="400" style="margin: 0 auto; border-color:rgb(144,163,180);">
                        <p>
                            <span style="margin-left:40px; color:rgb(212,228,237);">이메일</span> 
                            <span style="margin-left:44px; color:white;">{{user.user_email}}</span>
                        </p>
                        
                        
                     </div>
                </div>
            </div>
            <!--학력-->
            <h4 style="color:#0f4e78">학력</h4>
            <table class="table">
                <tr>
                    <th>졸업연도</th>
                    <th>학교명</th>
                    <th>학위명</th>
                </tr>
                <tr>
                    <td>{{user.user_doctor_date|date:"Y/m/d"}}</td>
                    <td>{{user.user_doctor}}</td>
                    <td>공학박사</td>
                </tr>
                <tr>
                    <td>{{user.user_master_date|date:"Y/m/d"}}</td>
                    <td>{{user.user_master}}</td>
                    <td>공학석사</td>
                </tr>
                <tr>
                    <td>{{user.user_university_date|date:"Y/m/d"}}</td>
                    <td>{{user.user_university}}</td>
                    <td>공학사</td>
                </tr>
            </table>
            <!--실적-->
            <h4 style="color:#0f4e78">실적</h4>
            <table class="table">
                <tr>
                   <th>구분명</th>
                   <th>학술지명</th>
                   <th>연도</th>
                   <th>발행권페이지</th>
                </tr>
                {% for obj in objects %}
                    <tr>
                        <td>{{obj.performance.get_perf_type_display}}</td>
                        <td>{{obj.performance.perf_title|safe}}</td>
                        <td>{{obj.performance.perf_end|date:"Y/m/d"}}</td>
                        <td>{{obj.performance.perf_etc|safe}}</td>
                    </tr>
                {% endfor %}
                
            </table>
        </div>
        
    </div>
     
{% endblock %}