acin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('acinsite.urls')),
    path('document/', include('document.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acinsite/urls.py
from django.urls import path
from acinsite import views
app_name='Main'

urlpatterns=[
    path('',views.main, name="main"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    path('intro/',views.intro,name="intro"),
    path('professor/',views.professor,name="professor"),
    path('member/',views.member,name="member"),
    path('project/create/',views.create_project,name="create-project"),
    path('project/delete/<pk>/',views.delete_project,name="delete-project"),
    path('project/modify/list/',views.modify_list,name="modify-list"),
    path('project/ajax/',views.get_ajax_project,name="ajax-project"),
    path('project/',views.project,name="project"),
    path('project/<keyword>/',views.project,name="project"),
    path('gallery/write/',views.write_gallery,name="write-gallery"),
    path('gallery/',views.gallery,name="gallery"),
    path('gallery/detail/<int:pk>/',views.detail_gallery,name="detail-gallery"),
    path('gallery/delete/<int:pk>/',views.delete_gallery,name="delete-gallery"),
    #MYPAGE
    path('mypage/',views.mypage,name="mypage"),
    
    #게시판
    path('board/Viewboard/',views.Viewboard,name="Viewboard"),
    path('board/Writeboard/',views.Writeboard,name="Writeboard"),
    path('board/Viewboard/Boarddetail/<int:pk>',views.Boarddetail,name="Boarddetail"),
    path('board/Viewboard/Boarddetail/Deleteboard/<int:pk>',views.Deleteboard, name="Deleteboard"),
    path('board/Viewboard/Boarddetail/Editboard/<int:pk>',views.Editboard, name="Editboard"),

    #일일보고
    path('Today_Report_Today_Report_Board',views.Today_Report_Board, name="Today_Report_Board"),
    path('Write_Today_Report', views.Write_Today_Report,name="Write_Today_Report"),
    path('Today_Report_detail/<int:pk>/',views.Today_Report_detail,name="Today_Report_detail"),
    path('Today_Report_Edit/<int:pk>/',views.Today_Report_Edit,name="Today_Report_Edit"),
    path('Today_Report_Del/<int:pk>',views.Today_Report_Del,name="Today_Report_Del"),
    

]

document/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'document'
urlpatterns = [
    path('', views.main, name="document-main"),
    path('daily/write', ReportWrite.as_view(), name="document-report-write"),
    path('daily/read/<pk>', ReportRead.as_view(), name="document-report-read"),
    path("userlist", views.ajax_userlist, name="document-ajax-userlist")
]

acinsite/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from django_summernote import fields as summer_fields
from .models import User,Performance,User_perform,Board,Comment,Reply,Gallery,Gallery_reference, Today_Report

class PostForm(forms.ModelForm):
    board_content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Board
        fields = ('board_title','board_content','board_file')
        widget = { 
            
            'board_content' : forms.Textarea(attrs={'cols':100, 'rows':100}),
        }
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['board_file'].required = False
        self.fields['board_title'].widget.attrs.update({'class':'form-control'})

class Today_Report_Form(forms.ModelForm):
    Today_Report_content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Today_Report
        fields = ('Today_Report_title','Today_Report_content','Today_Report_file')
        widget = {

            'Today_Report_content' : forms.Textarea(attrs={'cols':100, 'rows':100}),
        }
    def __init__(self, *args, **kwargs):
        super(Today_Report_Form, self).__init__(*args, **kwargs)
        self.fields['Today_Report_file'].required = False
        self.fields['Today_Report_title'].widget.attrs.update({'class':'form-control'})

acinsite/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from acinsite.models import *
from acinsite.forms import  *
from django.utils import timezone
from datetime import datetime
#메인
def main(request):
    cur_date = datetime.now().date()
    gal_objs = Gallery.objects.all().order_by('-id')[0:4]
    board_objs = Board.objects.all().order_by('-id')[0:3]
    user_birthday = User.objects.all()
    today_birth_user = User.objects.filter(user_birthday__month=cur_date.month,
                                           user_birthday__day=cur_date.day)
    if today_birth_user:
        today_birth_user = today_birth_user[0]
    context = {
        'cur_date':cur_date,
        'gal_objs':gal_objs,
        'board_objs':board_objs,
        'user_birthday':user_birthday,
        'today_birth_user':today_birth_user
    }
    return render(request,'acinsite/main.html',context)
#로그인
def login(request):
    context = {
        'msg' : '',
    }
    if request.method == "POST":
        user_objs = User.objects.filter(
                        user_number = request.POST.get('user_id'),
                        user_pw = request.POST.get('user_pw')
                    )
        if user_objs:
            request.session['user_id']  = request.POST.get('user_id')
            request.session['user_pk']  = user_objs[0].pk
            request.session['user_name']= user_objs[0].user_name
            return redirect("/")
        else:
            context['msg'] = 'LoginFail'
    return render(request,'acinsite/login.html',context)

#로그아웃
def logout(request):
    if request.session.get('user_id') or request.session.get('user_name'):
        del request.session['user_id']
        del request.session['user_name']
        del request.session['user_pk']


    return redirect('/')
#소개 페이지
def intro(request):
    return render(request,'acinsite/intro.html')
#professor 페이지
def professor(request):
    user = get_object_or_404(User,user_rank=1)
    objects = User_perform.objects.filter(
                    user=user,
                    performance__perf_state=True
                ).order_by('-performance__perf_end')

    print(user)
    print(objects)
    context = {
        'user':user,
        'objects':objects,
    }
    return render(request,'acinsite/professor.html',context)
#멤버 패이지
def member(request):
    users = User.objects.exclude(user_rank=1).order_by('user_rank','user_birthday')
    print(users)
    context = {
        'users':users,
    }
    return render(request,'acinsite/member.html',context)

#프로젝트 메인
def project(request,keyword=None):
    perf_objs = None
    context = {}
    #진행중인 프로젝트
    if keyword == "proceeding":
        perf_objs = Performance.objects.filter(
                    perf_isProfessor=False,
                    perf_state=False
                ).order_by('-perf_start')
        context['type']='proceeding'
    #종료된 프로젝트
    else:
        year_list = []
        perf_objs = Performance.objects.filter(
                    perf_isProfessor=False,
                    perf_state=True
                ).order_by('-perf_end')

        for obj in perf_objs:
            year = obj.perf_end_year
            if not year in year_list:
                year_list.append(year)
        context['year_list']=year_list
        context['type']='finish'

    context['object_list']=perf_objs

    return render(request,'acinsite/project/project_list.html',context)
#ajax 요청 프로젝트
def get_ajax_project(request):
    object_list = None
    if request.POST.get('year') == "all":
        object_list = Performance.objects.filter(
                            perf_isProfessor=False,
                            perf_state=True).order_by('-perf_end')
    else:
        object_list = Performance.objects.filter(
                            perf_isProfessor=False,
                            perf_state=True,
                            perf_end_year=request.POST.get('year')).order_by('-perf_end')
    context = {
        'object_list':object_list
    }
    return render(request,'acinsite/project/ajax_project.html',context)

#프로젝트 생성
def create_project(request):
    if not request.session.get('user_id'):
        return redirect('/login')
    pk = request.GET.get('pk')
    print(pk)
    if request.method == "POST":
        perf_status = False
        start_date = None
        end_date = None
        end_year = None
        if pk:
            print("hello")
            obj = Performance.objects.get(pk=pk)
            obj.delete()

        if request.POST.get('project_status'):
            perf_status=True
        if request.POST.get("start_date") != "":
            start_date = request.POST.get("start_date")
        if request.POST.get("end_date") != "":
            end_date = request.POST.get("end_date")
            end_year = request.POST.get("end_date")[0:4]


        perf_obj = Performance.objects.create(
                        perf_title = request.POST.get('project_title'),
                        perf_type  = request.POST.get('project_type'),
                        perf_content=request.POST.get('project_content'),
                        perf_etc=request.POST.get('project_etc'),
                        perf_host=request.POST.get('project_host'),
                        perf_sponsor=request.POST.get('project_sponso'),
                        perf_state=perf_status,
                        perf_start=start_date,
                        perf_end=end_date,
                        perf_end_year=end_year,
                    )
        if request.FILES.get('file'):
            perf_obj.perf_file=request.FILES.get('file')
        else:
            perf_obj.perf_file=request.POST.get('old_file')
        perf_obj.save(update_fields=['perf_file'])

        for mem in request.POST.getlist('member'):
            if isNumber(mem):
                user = get_object_or_404(User, id=mem)
                User_perform.objects.create(user=user,performance=perf_obj)
            else:
                User_perform.objects.create(other_user=mem,performance=perf_obj)

        return redirect("/project")

    #GET 방식
    context={}

    obj=None

    if pk:
        obj = get_object_or_404(Performance,pk=pk)
        context['obj']=obj


    users = User.objects.all().order_by('user_rank','user_birthday')
    context['users']=users
    return render(request,'acinsite/project/create_project.html',context)

def modify_list(request):
    # GET
    if not request.session.get('user_id'):
        return redirect('/login')
    if request.method == "GET":
        object_list = Performance.objects.exclude(perf_isProfessor=True).order_by('perf_state')
        print(object_list)
        context = {
            'object_list':object_list,
        }
        return render(request,'acinsite/project/modify_list.html',context)


def delete_project(request,pk):
    obj = get_object_or_404(Performance,pk=pk)
    obj.delete()
    return redirect("/project/modify/list/")

def one_page_count(objs,page):
    total_row = 12
    start = total_row * (page-1)
    end   = total_row + start


    return objs.count(),objs[start:end]

def gallery(request):
    context = {}
    object_list = None
    total_count = None
    page = int(request.GET.get('page'))
    if request.GET.get('keyword') == "modify":
        user_id = request.session.get('user_id')
        user=get_object_or_404(User,user_number=user_id)
        objs=Gallery.objects.filter(user=user)
        total_count,object_list = one_page_count(objs,page)
        context['keyword'] = "modify"

    else:
        objs = Gallery.objects.all().order_by('-id')
        total_count,object_list = one_page_count(objs,page)


    context['object_list'] = object_list
    context['page'] = page
    context['total_count'] = total_count
    return render(request,'acinsite/gallery/gallery.html',context)

#갤러리 쓰기
def write_gallery(request):
    if not request.session.get('user_id'):
        return redirect('/login')
    context = {}
    pk = request.GET.get('pk')
    if request.method == "POST":
        atch_file = None
        files = []
        #기존 테이블 삭제
        if pk:
            Gallery.objects.get(pk=pk).delete()
        user = get_object_or_404(User,user_number=request.session.get('user_id'))
        if request.FILES.get('atchdFile'):
            atch_file = request.FILES.get('atchdFile')
        elif request.POST.get('atchdFile'):
            atch_file = request.POST.get('atchdFile')

        gal_obj = Gallery.objects.create(
                        user=user,
                        gal_title=request.POST.get('title'),
                        gal_file =atch_file,
                    )

        if request.FILES.getlist('file'):
            files=request.FILES.getlist('file')
        if request.POST.getlist('file-mfy'):
            files+=request.POST.getlist('file-mfy')


        for file in files:
            Gallery_reference.objects.create(
                gallery=gal_obj,
                gal_photo=file
            )
        return HttpResponse("성공")
    if pk:
        obj = get_object_or_404(Gallery,pk=pk)
        context['obj'] = obj

    return render(request,'acinsite/gallery/write_gallery.html',context)
def detail_gallery(request,pk):

    obj = get_object_or_404(Gallery,pk=pk)
    obj.gal_hits = obj.gal_hits + 1
    obj.save(update_fields=['gal_hits'])
    context = {
        'obj':obj,
    }
    return render(request,'acinsite/gallery/detail_gallery.html',context)
def delete_gallery(request,pk):
    obj = get_object_or_404(Gallery,pk=pk)
    obj.delete()
    return redirect('/gallery?page=1')
#숫자 이냐?
def isNumber(number):
    try:
        int(number)
        return True
    except ValueError:
        return False

#mypage
def mypage(request):
    user_id = request.session.get('user_id')
    user = User.objects.get(user_number=user_id)
    print(user)
    context = {
        'user':user,
    }
    return render(request,'acinsite/mypage/member_info.html',context)
def Viewboard(request):
    vb = Board.objects.all().order_by('-pk')

acinsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <!--부트스트랩-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'document/css/main.css' %}">
    <!--제이쿼리-->
    <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    {% block style %}
    {% endblock %}
    <style>
        *{margin:0; padding:0;}
        #container{
            width:1200px;
            margin:0 auto;
        }
        #header{
            position: relative;
            margin-top:20px;
            height:55px;
        }
        .header-item{
            float: left;
            
        }
        .header-text{
            margin-left:80px;
        }
        .header-item a{
            color:#555555;
        }
       
        #footer{
            width:100%;
            
            clear: both;
            background-color: rgb(51,51,51);
            margin-top:30px;
        
        }
        #footer p{
            float: left;
        }
       
        .depth{

        height:40px;
        text-align: right;
        padding-right: 160px;
        background: rgb(234,234,234);
        margin-top:20px;
        line-height: 40px;

        }
        .depth span{
        color:rgb(102,102,102);
        margin-left:10px;
        font-size: 15px;
        font-weight: bold;
        }
    </style>
</head>
<body>
    <div id="container">
        <div id="header">
            <div class="header-item">
                <a href="{% url 'Main:main' %}">
                    <img width="100" height="40" src="{% static 'img/logo.jpeg' %}">
                </a>
            </div>
            <div class="header-item header-text">
                <h4><a href="{% url 'Main:intro' %}">Introduction</a></h4>
            </div>
            <div class="header-item header-text">
                <h4><a href="{% url 'Main:professor' %}">Professor</a></h4>
            </div>
            <div class="header-item header-text">
                <h4><a href="{% url 'Main:member' %}">Member</a></h4>
            </div>
            <div class="header-item header-text">
                <h4><a href="{% url 'Main:project' %}">Project</a></h4>
            </div>
            <div class="header-item header-text">
                <h4><a href="{% url 'Main:Viewboard' %}">Board</a></h4>
            </div>
            {% if s_user %}
                <div class="header-item header-text">
                    <h4><a href="{% url 'document:document-main' %}">결재</a><span class="badge-jy">{{report_cnt}}</span></h4>
                    
                </div>
            {% endif %}
            
            <div class="header-item" style="position: absolute; right:0px;">
                {% if request.session.user_id %}
                    <h4>
                            
                        <i class="glyphicon glyphicon-user"></i>
                        <a style="padding-right:10px;"  style="color:black"><b>{{ request.session.user_name }}</b></a>
                        <a href="{% url 'Main:logout' %}" style="color:black"><b>로그아웃</b></a>
                    </h4>
                {% else %}
                    
                    <h4><a href="{% url 'Main:login' %}" style="color:black;"><b>로그인</b></a></h4>
                {% endif %}    
            </div>
        </div>
        
       
             
    </div>
    {% block slider %}
    {% endblock %}
    {% block depth %}

    {% endblock %}
    <div style="width:1200px; margin:0 auto;">
        {% block content %}

        {% endblock %}    
    </div>
    <hr>

    <div id="footer" class="text-center">
            <p class="col-md-4"><img width="90" height="30" src="{% static 'img/logo.jpeg' %}"></p>
            <p class="col-md-4">
                    연구실 위치 : 청주대학교 이공대 구관 07-326호<br>
                    연구실 관련 문의 - 연락처 : 043-229-8496<br>
                                    Email : syr94@daum.net
            </p>
            <p class="col-md-4">
                <img height="30" src="{% static 'img/cjubiglogo.png' %}">
            </p>
    </div>
</body> 
</html>